<template>
  <!-- eslint-disable max-len -->
  <div>
    <h2>Account</h2>

    <div class="container">
      <transition name="translate">
        <!-- Authenticated -->
        <div v-if="accessToken && user" key="logged-in" class="logged-in">
          <div class="row row--justify-start row-items-start">
            <SeeMyProfileButton size="lg" />
            <div class="details">
              <h3>Logged in as <b>{{ user.name }}</b></h3>
              <div class="actions row row--justify-start row-items-start">
                <ButtonRefresh />
                <ButtonLogout />
              </div>
            </div>
          </div>
          <div class="row row--justify-between row--items-center">
            <p>Login out here will not remove the access token generated by <b>AniList</b>. Please go to your <a href="https://anilist.co/settings/apps" title="Open your settings page"><strong>Settings > Apps</strong></a> page and revoke the <b>AniListSearch</b> app for a complete logout.</p>
          </div>
        </div>

        <!-- Not authenticated -->
        <div v-else key="logged-out" class="logged-out">
          <div class="col col--justify-between col--items-start h-full">
            <div>
              <h3>You are currently not logged in.</h3>
              <p>Log in to enable search on your personal Anime and Manga lists.</p>
            </div>
            <div class="actions">
              <ButtonLogin />
            </div>
          </div>
        </div>
      </transition>
    </div>
  </div>
  <!-- eslint-enable max-len -->
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { State } from 'vuex-class';
import ButtonLogin from '@/components/auth/ButtonLogin.vue';
import ButtonLogout from '@/components/auth/ButtonLogout.vue';
import ButtonRefresh from '@/components/auth/ButtonRefresh.vue';
import SeeMyProfileButton from '@/components/auth/SeeMyProfileButton.vue';

@Component({
  components: {
    ButtonLogin,
    ButtonLogout,
    ButtonRefresh,
    SeeMyProfileButton,
  },
})
export default class UserSettings extends Vue {
  /**
   * Access token from store.
   */
  @State accessToken!: string | null;

  /**
   * User data from store.
   */
  @State user!: AniListSearch.AniList.User | null;
}
</script>

<style lang="scss" scoped>
.container {
  height: 135px;
  position: relative;
}

.logged-in,
.logged-out {
  height: 105px;
  position: absolute;
}

.logged-in {
  .details {
    padding-left: 1.5rem;
  }

  .actions {
    > * {
      margin-right: 1rem;
    }
  }
}

.note {
  margin-top: 1rem;
}
</style>
