<template>
  <!-- eslint-disable max-len -->
  <div id="settings__account">
    <h2>Account</h2>

    <div class="container">
      <!-- Authenticated -->
      <div v-if="accessToken" class="logged-in">
        <div class="row row--justify-start row-items-start">
          <SeeMyProfileButton size="lg" />
          <div class="logged-in__details">
            <h3>Logged in as <b>{{ user.name }}</b></h3>
            <div class="logged-in__details__actions row row--justify-start row-items-start">
              <ButtonRefresh />
              <ButtonLogout />
            </div>
          </div>
        </div>
        <div class="row row--justify-between row--items-center">
          <p class="note">Login out here will not remove the access token generated by <b>AniList</b>. Please go to your <a href="https://anilist.co/settings/apps" title="Open your settings page"><strong>Settings > Apps</strong></a> page and revoke the <b>AniSearch</b> app for a complete logout.</p>
        </div>
      </div>

      <!-- Not authenticated -->
      <div v-else class="logged-out">
        <div class="row row--justify-between row--items-center">
          <div>
            <h3>You are currently not logged in.</h3>
            <p>Log in to enable search on your personal Anime and Manga lists.</p>
          </div>
          <div class="logged-out__actions">
            <ButtonLogin />
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- eslint-enable max-len -->
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { State } from 'vuex-class';
import ButtonLogin from '@/components/auth/ButtonLogin.vue';
import ButtonLogout from '@/components/auth/ButtonLogout.vue';
import ButtonRefresh from '@/components/auth/ButtonRefresh.vue';
import SeeMyProfileButton from '@/components/auth/SeeMyProfileButton.vue';

@Component({
  components: {
    ButtonLogin,
    ButtonLogout,
    ButtonRefresh,
    SeeMyProfileButton,
  },
})
export default class UserSettings extends Vue {
  /**
   * Access token from store.
   */
  @State accessToken!: string|null;

  /**
   * User data from store.
   */
  @State user!: AniSearch.AniList.Schema.User|null;
}
</script>

<style lang="scss" scoped>
#settings__account {
  .logged-in {
    &__details {
      padding-left: 1.5rem;

      &__actions {
        > * {
          margin-right: 1rem;
        }
      }
    }
  }

  .logged-out {
    &__actions {
      padding: 0 2rem 0 2.5rem;
    }
  }

  .note {
    margin-top: 1rem;
  }
}
</style>
